services:


  curriculumadapter.api:
    image: ${DOCKER_REGISTRY-}curriculumadapterapi
    build:
      context: .
      dockerfile: CurriculumAdapter.API/Dockerfile
    ports:
      - 8080:8080
      - 8081:8081
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https-certs/aspnetcore.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=iqwdf93jr9023njrm0923mf2qom3


  adminer:
   container_name: adminer-container
   image: adminer
   restart: always
   ports:
    - 8082:8080 