// <auto-generated />
using System;
using CurriculumAdapter.API.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CurriculumAdapter.API.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250619230349_AddAddressColumnInPaymentInfosTable")]
    partial class AddAddressColumnInPaymentInfosTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CurriculumAdapter.API.Models.FeedbackModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FeedbackText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("feedback_text");

                    b.Property<double>("Stars")
                        .HasColumnType("double precision")
                        .HasColumnName("stars");

                    b.HasKey("Id");

                    b.ToTable("feedbacks", (string)null);
                });

            modelBuilder.Entity("CurriculumAdapter.API.Models.Logs.FeatureUsageLogModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FeatureName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("feature_name");

                    b.Property<DateTime>("UsageDate")
                        .HasColumnType("DATE")
                        .HasColumnName("usage_date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("feature_usage_logs", (string)null);
                });

            modelBuilder.Entity("CurriculumAdapter.API.Models.PaymentInfosModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("AdressNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("adress_number");

                    b.Property<string>("CpfCnpj")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cpf_cnpj");

                    b.Property<string>("CreditCardToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("credit_card_token");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("postal_code");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("payment_infos", (string)null);
                });

            modelBuilder.Entity("CurriculumAdapter.API.Models.UserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AsaasCustomerId")
                        .HasColumnType("text")
                        .HasColumnName("asaas_customer_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
