name: Deploy API to VPS Development Environment

on:
 workflow_dispatch:
 push:
  branches: ['development']
  


jobs:
 build:
  runs-on: ubuntu-latest
  environment: Dev

  steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4

    - name: Restore Dependencies
      run: dotnet restore ${{ github.workspace }}/CurriculumAdapter/CurriculumAdapter.sln

    - name: Build
      run: dotnet build --no-restore ${{ github.workspace }}/CurriculumAdapter/CurriculumAdapter.sln

    - name: Publish Build
      run: dotnet publish -c Release -o ${{ github.workspace }}/out ${{ github.workspace }}/CurriculumAdapter/CurriculumAdapter.API/CurriculumAdapter.API.csproj

    - name: Login Docker
      uses: docker/login-action@v3.5.0
      with: 
       Username: ${{ secrets.DOCKERHUB_USERNAME }}
       Password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build Docker Image
      run: |
       cd ${{ github.workspace }}/CurriculumAdapter
       docker build -t ${{ secrets.DOCKERHUB_REPO }}:${{ github.sha }} -f ${{ github.workspace }}/CurriculumAdapter/CurriculumAdapter.API/Dockerfile .
       cd ..

    - name: Push image to DockerHub
      run: docker push ${{ secrets.DOCKERHUB_REPO }}:${{ github.sha }}
      
    - name: Deploy to VPS
      run: |
       echo "Initializing ssh-agent"
       eval "$(ssh-agent -s)"
       
       echo "Saving ssh private key into ssh-agent memory"
       echo "${{ secrets.VPS_PRIVATE_KEY }}" | ssh-add -

       echo "Accessing VPS via SSH and creating the docker container"
       ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} \
       "docker pull ${{ secrets.DOCKERHUB_REPO }}:${{ github.sha }} && \
        docker stop ca_api_dev || true && \
        docker container rm ca_api_dev || true && \
        docker run -d --name ca_api_dev -p 8080:8080 -p 8083:8083 --env ASPNETCORE_Kestrel__Certificates__Default__Path=/https-certs/aspnetcore.pfx --env ASPNETCORE_Kestrel__Certificates__Default__Password=iqwdf93jr9023njrm0923mf2qom3 --env DATABASE_CONNECTION=${{ secrets.DATABASE_CONNECTION }} --env RECAPTCHA_SECRET_KEY=${{ secrets.RECAPTCHA_SECRET_KEY }} --env QDRANT_HOST=${{ secrets.QDRANT_HOST }} --env OPEN_AI_API_KEY=${{ secrets.OPEN_AI_API_KEY }} --env JWT_SECRET=${{ secrets.JWT_SECRET }} --env CORS_LOCALHOST_URL=${{ secrets.CORS_LOCALHOST_URL }} --env CORS_CLIENT_URL=${{ secrets.CORS_CLIENT_URL }} --env ASSISTANT_ID_GPT_41_MINI=${{ secrets.ASSISTANT_ID_GPT_41_MINI }} --env ASAAS_API_KEY_PROD=${{ secrets.ASAAS_API_KEY_PROD }} --env ADVISOR_ASSISTANT_ID=${{ secrets.ADVISOR_ASSISTANT_ID }} --network ca-network-dev ${{ secrets.DOCKERHUB_REPO }}:${{ github.sha }}"
        "

  